### ISSUE TITLE
Chatbot: Dynamic ground truths

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity-os-marketplace/command-ask#13]
https://github.com/ubiquity-os-marketplace/command-ask/blob/e45db813be018fe8772414ca6ec7cbba3b8e55e1/src/adapters/openai/helpers/completions.ts#L40-L42

https://github.com/ubiquity-os-marketplace/command-ask/blob/e45db813be018fe8772414ca6ec7cbba3b8e55e1/src/handlers/ask-llm.ts#L70

I think these should be dynamic, I don't have super clear context on them but from what I can surmise they'd benefit from it.

- Are they restricted to being one-word strings? What's the max length if not? How many truths can we provide/what's the optimal amount?
- Are they supposed to embody the org, the incoming query or the task in relation to the current `@ubqbot` command or the fully built `formattedChat` that includes all context?

I think we have GPT-4o build our array based on the input it's given because:
1. Truths are dynamic and based on either A) fully built/initial incoming user query B) built around the payload issue spec or whatever C) task spec when considering code review
2. We need a quick response imo, a huge spec to truth followed by the spec + the entire diff both to `o1` may be too long to wait for little added benefit.

**Comment by Keyrxng** [comment]
for `@ubqbot` we can pull the tech stacks dynamically for the partner per repo by:

- fetching the repo's language stats and passing them in, we could adjust the prompt to give more weight to the higher percentage language present
- We can use the `package.json` to find out what libs/frameworks etc the repo uses

this covers tech stacks and frameworks, we could leverage the readme too which might include more but `package.json` and language stats should do it imo. What do you think?

**Comment by Keyrxng** [comment]
Just over 4 hours at this point in terms of time - awaiting review. And I'm unsure of priority.

**Comment by Keyrxng** [comment]
@0x4007 Can you price and regen the reward please?

**Comment by Keyrxng** [comment]
Good catch, needs wrapped.

It either should be included in the next PR to be merged mine or yours, or addressed in #17, whatever approach you think is best.

**Comment by Keyrxng** [comment]
No it was definitely me I wrote that fetch call, everyone makes mistakes we're only human after all.

**Comment by 0x4007** [comment]
> @0x4007 Can you price and regen the reward please?

These need to be approved to be funded before work is done and expecting to get paid for it.

**Comment by Keyrxng** [comment]
> > @0x4007 Can you price and regen the reward please?
> 
> These need to be approved to be funded before work is done and expecting to get paid for it.

It never produced a $200 reward and I claimed the $53 so I guess it worked out
