### ISSUE TITLE
Missing context

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity-os-marketplace/command-ask#26]
It looks like `/ask` is not working as it should be

1. Hallucinating against the spec because it never pulled the spec in.
2. The README inside the conversation block without distinction makes it appear as if it's part of the current conversation which also should state Pull Request in the header but appears as Issue
3. It looks like it hasn't pulled in the PR diff at all

Please see this [run](https://github.com/ubiquity-os-marketplace/command-ask/actions/runs/11605147726/job/32315045572)

_related [context](https://github.com/ubiquity-os/permit-generation/pull/96#issuecomment-2448904538)_

**Comment by Keyrxng** [comment]
I'll look into it tomorrow as I may have caused it with the refactor but I didn't touch the issue fetching or context window logic but either way I'll resolve whatever the issue is if not resolved by then

**Comment by rndquu** [comment]
@Keyrxng Pls don't start unfunded github issues
