### ISSUE TITLE
env var fix

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity-os-marketplace/command-ask#8]
`OPENAI_API_KEY` is actually now `OPENROUTER_API_KEY` as far as I can tell

My OpenAI key failed to be authenticated but things worked after I used an OpenRouter key.

Refs to this env var should be updated and readme updated to let contributors know to use this.

**Comment by 0x4007** [comment]
Yes i set this as an org key which can be accessed by any repo in this org. 

Their logic needs to handle requesting the correct model for their needs.

**Comment by Keyrxng** [comment]
I just copy/pasted the plugin config that's currently installed which might lead to confusion if that's how a partner/contributor might also get their config.
